-- Add About Page sections to CMS
INSERT INTO content_sections (section_key, title, content, media_urls) VALUES

-- Mission Section
('about_mission',
'{"en": "Our Mission", "fr": "Notre Mission", "rw": "Intego Yacu", "ar": "مهمتنا"}',
'{"en": "At Umbrella for Vulnerable, we implement comprehensive programs including social protection, emergency relief, education, faith-based initiatives, women & youth empowerment, and family protection to support vulnerable families and communities.|Through our work across different communities, we have witnessed the everyday struggles vulnerable families face, and we are committed to addressing these challenges through coordinated and comprehensive support programs.", "fr": "Chez Umbrella for Vulnerable, nous mettons en œuvre des programmes complets comprenant la protection sociale, l''aide d''urgence, l''éducation, les initiatives confessionnelles, l''autonomisation des femmes et des jeunes et la protection de la famille pour soutenir les familles et les communautés vulnérables.|Grâce à notre travail dans différentes communautés, nous avons été témoins des luttes quotidiennes auxquelles sont confrontées les familles vulnérables, et nous nous engageons à relever ces défis par le biais de programmes de soutien coordonnés et complets.", "rw": "Kuri Umbrella for Vulnerable, turashyira mu bikorwa gahunda zuzuye zirimo kurinda imibereho, ubufasha bwihutirwa, uburezi, ibikorwa bishingiye ku idini, guha imbaraga abagore n''urubyiruko, no kurinda imiryango kugira ngo dufashe imiryango yoroshye n''abaturage.|Binyuze mu kazi kacu mu miryango itandukanye, twabonye imirwano ya buri munsi imiryango yoroshye ihura na yo, kandi twiyemeje gukemura izo mbogamizi binyuze muri gahunda z''inkunga zihuriweho kandi zuzuye.", "ar": "في مظلة الضعفاء، ننفذ برامج شاملة تشمل الحماية الاجتماعية والإغاثة الطارئة والتعليم والمبادرات القائمة على الإيمان وتمكين المرأة والشباب وحماية الأسرة لدعم الأسر والمجتمعات الضعيفة.|من خلال عملنا في مختلف المجتمعات، شهدنا الصراعات اليومية التي تواجهها الأسر الضعيفة، ونحن ملتزمون بمعالجة هذه التحديات من خلال برامج دعم منسقة وشاملة."}',
'["/ufvimages/47.jpg"]'),

-- Vision Section
('about_vision',
'{"en": "Our Vision", "fr": "Notre Vision", "rw": "Icyerekezo Cyacu", "ar": "رؤيتنا"}',
'{"en": "A community where vulnerable families have access to social protection, emergency relief, quality education, spiritual guidance, and empowerment opportunities for sustainable development and self-reliance.", "fr": "Une communauté où les familles vulnérables ont accès à la protection sociale, à l''aide d''urgence, à une éducation de qualité, à des conseils spirituels et à des opportunités d''autonomisation pour un développement durable et l''autosuffisance.", "rw": "Umuryango aho imiryango yoroshye igira uburyo bwo kurindwa n''imibereho, ubufasha bwihutirwa, uburezi bwiza, ubuyobozi bw''umwuka, n''amahirwe yo kwigenera kugira ngo iterambere rirambe kandi bigenere.", "ar": "مجتمع حيث تتمتع الأسر الضعيفة بإمكانية الوصول إلى الحماية الاجتماعية والإغاثة الطارئة والتعليم الجيد والتوجيه الروحي وفرص التمكين للتنمية المستدامة والاعتماد على الذات."}',
'[]'),

-- Challenges
('about_challenges',
'{"en": "Challenges We Address", "fr": "Défis que nous relevons", "rw": "Ibibazo Dukemura", "ar": "التحديات التي نواجهها"}',
'{"en": "Poverty & Vulnerability|Extreme poverty affecting vulnerable families, orphans, widows, and disadvantaged households|Emergency Situations|Natural disasters, crises, and urgent community needs requiring immediate humanitarian response|Limited Opportunities|Lack of access to education, vocational training, and economic empowerment opportunities", "fr": "Pauvreté et vulnérabilité|Pauvreté extrême affectant les familles vulnérables, les orphelins, les veuves et les ménages défavorisés|Situations d''urgence|Catastrophes naturelles, crises et besoins communautaires urgents nécessitant une réponse humanitaire immédiate|Opportunités limitées|Manque d''accès à l''éducation, à la formation professionnelle et aux opportunités d''autonomisation économique", "rw": "Ubukene n''Ubworoshye|Ubukene bukabije bugira ingaruka ku miryango yoroshye, imfubyi, abapfakazi, n''imiryango ibangamiwe|Ibihe by''Ihutirwa|Ibiza, ibibazo, n''ibikenewe byihutirwa mu muryango bisaba igisubizo cyihuse cy''ubuntu|Amahirwe Make|Kubura uburyo bwo kubona uburezi, amahugurwa y''umwuga, n''amahirwe yo kwigenera mu bukungu", "ar": "الفقر والضعف|الفقر المدقع الذي يؤثر على الأسر الضعيفة والأيتام والأرامل والأسر المحرومة|حالات الطوارئ|الكوارث الطبيعية والأزمات واحتياجات المجتمع العاجلة التي تتطلب استجابة إنسانية فورية|فرص محدودة|عدم الوصول إلى التعليم والتدريب المهني وفرص التمكين الاقتصادي"}',
'[]'),

-- Response
('about_response',
'{"en": "Our response", "fr": "Notre réponse", "rw": "Igisubizo Cyacu", "ar": "استجابتنا"}',
'{"en": "These challenges require comprehensive, coordinated responses that address both immediate needs and long-term development. Our approach combines direct assistance with capacity building and empowerment.|We implement six core programs that work together to provide holistic support: social protection, emergency relief, education, faith-based initiatives, women & youth empowerment, and family protection programs.", "fr": "Ces défis nécessitent des réponses complètes et coordonnées qui répondent à la fois aux besoins immédiats et au développement à long terme. Notre approche combine l''assistance directe avec le renforcement des capacités et l''autonomisation.|Nous mettons en œuvre six programmes de base qui travaillent ensemble pour fournir un soutien holistique: protection sociale, aide d''urgence, éducation, initiatives confessionnelles, autonomisation des femmes et des jeunes et programmes de protection de la famille.", "rw": "Ibi bibazo bisaba ibisubizo byuzuye kandi bihuriweho bikemura ibikenewe byihutirwa n''iterambere rirambye. Uburyo bwacu buhuza ubufasha butaziguye n''ubushobozi bwo kubaka no guha imbaraga.|Turashyira mu bikorwa gahunda esheshatu z''ingenzi zikorana kugira ngo dutange inkunga yuzuye: kurinda imibereho, ubufasha bwihutirwa, uburezi, ibikorwa bishingiye ku idini, guha imbaraga abagore n''urubyiruko, na gahunda zo kurinda imiryango.", "ar": "تتطلب هذه التحديات استجابات شاملة ومنسقة تعالج الاحتياجات الفورية والتنمية طويلة الأجل. يجمع نهجنا بين المساعدة المباشرة وبناء القدرات والتمكين.|ننفذ ستة برامج أساسية تعمل معًا لتوفير الدعم الشامل: الحماية الاجتماعية والإغاثة الطارئة والتعليم والمبادرات القائمة على الإيمان وتمكين المرأة والشباب وبرامج حماية الأسرة."}',
'["/ufvimages/34.jpg"]'),

-- Core Values
('about_values',
'{"en": "Our Core Values", "fr": "Nos valeurs fondamentales", "rw": "Indangagaciro Zacu z''Ingenzi", "ar": "قيمنا الأساسية"}',
'{"en": "Integrity|Upholding honesty and transparency in all our work|Compassion|Showing empathy and care for every family we serve|Community|Building strong partnerships and local engagement|Empowerment|Equipping communities with knowledge and tools", "fr": "Intégrité|Maintenir l''honnêteté et la transparence dans tout notre travail|Compassion|Faire preuve d''empathie et de soins pour chaque famille que nous servons|Communauté|Construire des partenariats solides et un engagement local|Autonomisation|Équiper les communautés de connaissances et d''outils", "rw": "Ubunyangamugayo|Kubahiriza ubunyangamugayo no gusobanura mu kazi kwacu kwose|Impuhwe|Kwerekana impuhwe n''ubwitange ku miryango yose dukorera|Umuryango|Kubaka ubufatanye bukomeye n''uruhare rw''abaturage|Guha Imbaraga|Guha abaturage ubumenyi n''ibikoresho", "ar": "النزاهة|الحفاظ على الصدق والشفافية في جميع أعمالنا|التعاطف|إظهار التعاطف والرعاية لكل عائلة نخدمها|المجتمع|بناء شراكات قوية ومشاركة محلية|التمكين|تزويد المجتمعات بالمعرفة والأدوات"}',
'[]'),

-- Partners
('about_partners',
'{"en": "Our Partners", "fr": "Nos Partenaires", "rw": "Abafatanyabikorwa Bacu", "ar": "شركاؤنا"}',
'{"en": "We collaborate with these amazing organizations to create lasting impact in communities across Rwanda.", "fr": "Nous collaborons avec ces organisations incroyables pour créer un impact durable dans les communautés du Rwanda.", "rw": "Dufatanije n''imiryango itangaje kugira ngo dukore ingaruka zirambye mu miryango yo mu Rwanda.", "ar": "نتعاون مع هذه المنظمات الرائعة لخلق تأثير دائم في المجتمعات في جميع أنحاء رواندا."}',
'[]');
